<?php
    $featuredProductsEnable = Mage::getStoreConfig('bestseller_products/settings/enable');
    $featuredProductsTitle  = Mage::getStoreConfig('bestseller_products/settings/title');
    $featuredProductsAutoPlay = Mage::getStoreConfig('bestseller_products/settings/auto_play');
    $featuredProductsSingle = Mage::getStoreConfig('bestseller_products/settings/single');
    $featuredProducts1Column = Mage::getStoreConfig('bestseller_products/settings/items_1column');
    $featuredProducts2Column = Mage::getStoreConfig('bestseller_products/settings/items_2column');
    $featuredProducts3Column = Mage::getStoreConfig('bestseller_products/settings/items_3column');
    $this->getProducts();
    $_productCollection = $this->getProductCollection();
    $_productsCount = count($_productCollection); $animationsEnable = Mage::getStoreConfig('illusion_settings/layout/animations_enable');

?>
<?php if($featuredProductsEnable && count($_productCollection)):?>
    <section class="<?php if(!$this->getData('title')):?> p_top_35 p_bottom_30 <?php else:?> p_bottom_30 <?php endif;?>">
        <div class="container">
            <?php if($this->getData('title')):?>
                <h3 class="fw_light color_dark m_bottom_35 t_align_c" <?php if($animationsEnable):?>data-appear-animation="bounceInLeft"<?php endif;?>><?php echo $this->getData('title');?></h3>
            <?php endif;?>
            <div class="relative m_xs_bottom_30">
                <div class="row">
                    <div class="owl-carousel t_xs_align_c featured_products" data-nav="fproducts_nav_best_" data-plugin-options='{"singleItem":<?php echo $featuredProductsSingle;?>,"itemsCustom":[[992,<?php echo $featuredProducts1Column;?>],[768,<?php echo $featuredProducts2Column;?>],[600,<?php echo $featuredProducts3Column;?>],[10,1]],"autoPlay":<?php echo $featuredProductsAutoPlay;?>}'>
                    <?php $i = 0;?>
                    <?php foreach($_productCollection as $_product):?>
                        <figure class="fp_item t_align_c d_xs_inline_b col-lg-12 col-md-12 col-sm-12" <?php if($animationsEnable):?>data-appear-animation="bounceIn"<?php endif;?> data-appear-animation-delay="<?php echo ++$i*200;?>">
                            <div class="relative r_corners d_xs_inline_b d_mxs_block wrapper m_bottom_23 t_xs_align_c">
                                <a href="<?php echo $_product->getProductUrl();?>">
                                    <div class="fp_images relative">
                                        <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'small_image')->resize(270,370)->setQuality(90);?>" alt="" class="tr_all">
                                        <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(270,370)->setQuality(90);?>" alt="" class="tr_all">
                                    </div>
                                </a>
                                <?php echo Mage::helper('illusion_settings')->getNewSpecialBlock($_product);?>
                                <div class="quick_btn">
                                    <a href="<?php echo $this->getUrl('ajaxquickview/product/quickview/id/' . $_product->getId()) ?>" class="ajax"><i class="icon-eye-1"></i><?php echo $this->__('Quick View') ?></a>
                                </div>
                            </div>
                            <figcaption class="inColumn">
                                <h6 class="m_bottom_5"><a href="<?php echo $_product->getProductUrl();?>" class="color_dark"><?php echo $_product->getName();?></a></h6>
                                <?php $categorySettings = Mage::getStoreConfig('illusion_settings/product_box_settings/category');?>
                                <?php if($categorySettings):?>
                                    <?php $productCategories = $_product->getCategoryCollection();?>
                                    <?php $index = 0;?>
                                    <?php foreach($productCategories as $productCategory):?>
                                        <?php $productCategoryId = $productCategory->getId();?>
                                        <?php $productCategoryItem = Mage::getModel('catalog/category')->load($productCategoryId);?>
                                        <?php if($index++ > 0):?>
                                            <span color="color_grey">/</span>
                                        <?php endif;?>
                                        <a href="<?php echo $productCategoryItem->getUrl();?>" class="fs_medium color_grey d_inline_b m_bottom_3"><i><?php echo $productCategoryItem->getName();?></i></a>
                                    <?php endforeach;?>
                                <?php endif;?>

                                <div class="im_half_container m_bottom_10">
                                    <?php $ratings = $this->getReviewsSummaryHtml($_product, 'short');?>
                                    <?php $priceSettings = Mage::getStoreConfig('illusion_settings/product_box_settings/price');?>
                                    <?php if($priceSettings):?>
                                        <div class="color_dark d_sm_block w_sm_full d_xs_inline_m w_xs_half_column fw_ex_bold half_column <?php if($ratings):?> d_inline_m m_0 <?php endif;?> t_align_c tr_all animate_fctl fp_price with_ie product_listing_color">
                                            <?php echo $this->getPriceHtml($_product, true); ?>
                                        </div>
                                    <?php endif;?>

                                    <?php $ratingSettings = Mage::getStoreConfig('illusion_settings/product_box_settings/rating');?>
                                    <?php if($ratingSettings && $this->getRatingSummary($_product) && $ratings ):?>
                                        <div class="half_column d_sm_block w_sm_full d_xs_inline_m w_xs_half_column t_sm_align_c t_xs_align_r d_inline_m t_align_r tr_all animate_fctr with_ie">
                                            <?php echo $ratings; ?>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="clearfix">
                                    <div class="half_column w_md_full m_md_bottom_10 animate_fctl tr_all f_left f_md_none with_ie">
                                        <?php if($_product->isSaleable()): ?>
                                            <a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="button_type_6 d_inline_b color_pink transparent r_corners vc_child tr_all add_to_cart_button product_listing_addtocart">
                                                <span class="d_inline_m clerarfix">
                                                    <i class="icon-basket f_left m_right_10 fs_large"></i>
                                                    <span class="fs_medium"><?php echo $this->__('Add to Cart') ?></span>
                                                </span>
                                            </a>
                                        <?php endif;?>
                                    </div>
                                    <div class="half_column w_md_full animate_fctr tr_all f_left f_md_none clearfix with_ie <?php if(!$_product->isSaleable()) echo 'w_65' ;?>">
                                        <?php $compareSettings = Mage::getStoreConfig('illusion_settings/product_box_settings/compare');?>
                                        <?php if($compareSettings):?>
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product) ): ?>
                                                <a href="<?php echo $_compareUrl ?>" class="add_to_compare button_type_6 relative tooltip_container f_right f_md_none d_md_inline_b d_block color_dark r_corners vc_child tr_all color_blue_hover t_align_c"><i class="icon-docs d_inline_m fs_large"></i><span class="d_block r_corners color_default tooltip fs_small fw_normal tr_all">Add to Compare</span></a>
                                            <?php endif;?>
                                        <?php endif;?>

                                        <?php $wishlistSettings = Mage::getStoreConfig('illusion_settings/product_box_settings/wishlist');?>
                                        <?php if ($this->helper('wishlist')->isAllow() && $wishlistSettings) : ?>
                                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="add_to_wishlist button_type_6 m_left_5 relative tooltip_container f_right f_md_none d_md_inline_b d_block color_dark r_corners vc_child tr_all color_purple_hover t_align_c m_right_5 m_md_right_0">
                                                <i class="icon-heart d_inline_m fs_large"></i>
                                                <span class="d_block r_corners color_default tooltip fs_small fw_normal tr_all">Add to Wishlist</span></a>
                                        <?php endif;?>
                                    </div>
                                </div>
                            </figcaption>
                        </figure>
                    <?php endforeach;?>
                    </div>
                </div>

                <?php if($_productsCount > 3):?>
                    <button class="icon_wrap_size_4 circle color_grey_light carousel_color carousel_border_color tr_all color_blue_hover fproducts_nav_best_prev d_md_none" <?php if($animationsEnable):?>data-appear-animation="fadeIn"<?php endif;?>>
                        <i class="icon-left-open-big"></i>
                    </button>
                    <button class="icon_wrap_size_4 circle color_grey_light carousel_color carousel_border_color tr_all color_blue_hover fproducts_nav_best_next d_md_none" <?php if($animationsEnable):?>data-appear-animation="fadeIn"<?php endif;?>>
                        <i class="icon-right-open-big"></i>
                    </button>
                <?php endif;?>
            </div>
        </div>
    </section>
<?php endif;?>