<section class="section_offset">
    <div class="container">
        <h3 class="color_dark fw_light m_bottom_15 t_align_c" data-appear-animation="bounceInLeft">Our Brands</h3>
        <p class="m_bottom_35 t_align_c" data-appear-animation="bounceInLeft" data-appear-animation-delay="200">Donec eget tellus non erat lacinia fermentum. </p>
        <div class="relative" data-appear-animation="bounceInLeft" data-appear-animation-delay="400">
            <div class="t_xs_align_c">
                <div class="owl-carousel clients brands t_align_c" data-plugin-options='{"pagination":true,"transitionStyle" : "backSlide"}' data-nav="c_nav_">
                    <!--item-->
                    <div>
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_1.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_2.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_3.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_4.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_5.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_6.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--item-->
                    <div>
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_1.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_2.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_3.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_4.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_5.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_6.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--item-->
                    <div>
                        <div class="row">
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_1.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_2.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 m_bottom_20 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_3.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_4.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_5.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-4 f_mxs_none w_mxs_full m_mxs_bottom_10">
                                <div class="clients_item db_xs_centered wrapper relative r_corners d_xs_block d_mxs_inline_b">
                                    <a href="#" class="d_block translucent tr_all wrapper r_corners">
                                        <img src="<?php echo $this->getSkinUrl('images/client_logo_6.jpg');?>" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--carousel nav-->
            <button class="icon_wrap_size_5 circle color_grey_light carousel_color carousel_border_color tr_all color_blue_hover c_nav_prev nav_type_2 d_md_none">
                <i class="icon-left-open-big"></i>
            </button>
            <button class="icon_wrap_size_5 circle color_grey_light carousel_color carousel_border_color tr_all color_blue_hover c_nav_next nav_type_2 d_md_none">
                <i class="icon-right-open-big"></i>
            </button>
        </div>
    </div>
</section>