<?php
    /** @var $currentCategory Mage_Catalog_Model_Category */
    $currentCategory = Mage::registry('current_category');
    $currentCategory->hasChildren();

?>
<?php if($currentCategory->hasChildren()):?>
    <?php
        $_childCategoryIds = $currentCategory->getChildren();
        $_childCategoryIds = explode(',',$_childCategoryIds);

        $categories = array();
        foreach($_childCategoryIds as $_childCategoryId) {
            $category = Mage::getModel('catalog/category')->load($_childCategoryId);
            $categories[$category->getName()] = array(
                'url' => $category->getUrl(),
                'img' => $category->getThumbnailUrl(true)
            );
        };
    ?>
    <div class="clearfix m_bottom_50 m_xs_bottom_15 t_xs_align_c child_categories p_bottom_5">
        <?php $i=0;?>
        <?php foreach($categories as $name => $data): ?>
            <a class="m_bottom_10 r_corners category_link w_xs_auto d_xs_inline_b f_xs_none m_xs_bottom_15 d_block f_left wrapper <?php if($i==0 || $i%5 != 0) {echo 'm_right_10'; $i=0;};?> t_align_c" href="<?php echo $data['url']; ?>" title="<?php echo $name; ?>" class>
                <img alt="<?php echo $name; ?>" src="<?php echo $this->helper('timage')->init($data['img'])->resize(166, 166); ?>"/>
                <p class="category_title bg_light_2 tr_all color_dark"><?php echo $name; ?></p>
            </a>
            <?php $i++;?>
        <?php endforeach;?>
    </div>
<?php endif;?>