<?php

$obj = new Mage_Catalog_Block_Navigation();
$storeCats = $obj->getStoreCategories();
//$current_cat    = $obj->getCurrentCategory();
//$current_cat    = (is_object($current_cat) ? $current_cat->getName() : '');
//
//foreach ($store_cats as $cat) {
//    if ($cat->getName() == $current_cat) {
//        echo '<li class="current"><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a>\n<ul>\n";
//        foreach ($obj->getCurrentChildCategories() as $subcat) {
//            echo '<li><a href="'.$this->getCategoryUrl($subcat).'">'.$subcat->getName()."</a></li>\n";
//        }
//        echo "</ul>\n</li>\n";
//    } else {
//        echo '<li><a href="'.$this->getCategoryUrl($cat).'">'.$cat->getName()."</a></li>\n";
//    }
//}

?>

<div class="m_bottom_40 m_xs_bottom_30">
    <h5 class="color_dark fw_light m_bottom_20"><?php echo $this->__('Categories') ?></h5>
    <ul class="categories_list">
        <?php foreach($storeCats as $cat):?>
            <li>
                <a class="color_dark tr_all d_block" href="<?php echo $this->getCategoryUrl($cat);?>">
                    <span class="icon_wrap_size_0 circle d_inline_m m_right_8 color_grey_light_5 tr_inherit">
                        <i class="icon-angle-right"></i>
                    </span>
                    <?php echo $cat->getName();?>
                </a>
                <?php $cat = Mage::getModel('catalog/category')->load($cat->getId());?>
                <?php $subCats = $cat->getChildren();?>
                <?php if(!empty($subCats)):?>
                    <ul class="fw_light d_none">
                        <?php foreach(explode(',',$subCats) as $subCatId):?>
                            <?php $_category = Mage::getModel('catalog/category')->load($subCatId);?>
                            <?php if($_category->getIsActive()):?>
                                <li>
                                    <a href="<?php echo $_category->getUrl();?>" class="d_block color_dark">
                                        <i class="icon-angle-right d_inline_m m_right_8 color_grey_light_5 fs_small tr_inherit"></i>
                                        <span class="d_inline_m"><?php echo $_category->getName();?></span>
                                    </a>
                                    <?php $cat = Mage::getModel('catalog/category')->load($_category->getId());?>
                                    <?php $subCats = $cat->getChildren();?>
                                    <?php if(!empty($subCats)):?>
                                        <ul class="fw_light fs_medium d_none">
                                        <?php foreach(explode(',',$subCats) as $subCatId):?>
                                            <?php $_category = Mage::getModel('catalog/category')->load($subCatId);?>
                                            <?php if($_category->getIsActive()):?>
                                                <li>
                                                    <a href="<?php echo $_category->getUrl();?>" class="d_block color_dark">
                                                        <i class="icon-angle-right d_inline_m m_right_8 color_grey_light_5 fs_small tr_inherit"></i>
                                                        <span class="d_inline_m"><?php echo $_category->getName();?></span>
                                                    </a>
                                                </li>
                                            <?php endif;?>
                                            <?php endforeach;?>
                                        </ul>
                                    <?php endif;?>
                                </li>
                            <?php endif;?>
                        <?php endforeach;?>
                    </ul>
                <?php endif;?>
            </li>
        <?php endforeach;?>
    </ul>
</div>