<ul class="hr_list d_inline_b social_icons header_social">

    <?php if($socialFacebook = $this->getBlockConfig('social/social_facebook')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialFacebook;?>" class=" facebook circle icon_wrap_size_1 d_block social_links_color"><i class="icon-facebook-1"></i></a></li>
    <?php endif;?>

    <?php if($socialTwitter = $this->getBlockConfig('social/social_twitter')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialTwitter;?>" class=" twitter circle icon_wrap_size_1 d_block social_links_color"><i class="icon-twitter-1"></i></a></li>
    <?php endif;?>

    <?php if($socialGPlus = $this->getBlockConfig('social/social_gplus')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialGPlus;?>" class=" googleplus circle icon_wrap_size_1 d_block social_links_color"><i class="icon-gplus-1"></i></a></li>
    <?php endif;?>

    <?php if($socialPinterest = $this->getBlockConfig('social/social_pinterest')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialPinterest;?>" class=" pinterest circle icon_wrap_size_1 d_block social_links_color"><i class="icon-pinterest"></i></a></li>
    <?php endif;?>

    <?php if($socialDribble = $this->getBlockConfig('social/social_dribble')):?>
    <li class="m_right_8"><a target="_blank" href="<?php echo $socialDribble;?>" class=" dribbble circle icon_wrap_size_1 d_block social_links_color"><i class="icon-dribbble"></i></a></li>
    <?php endif;?>

    <?php if($socialFlick = $this->getBlockConfig('social/social_flickr')):?>
    <li class="m_right_8"><a target="_blank" href="<?php echo $socialFlick;?>" class=" flickr circle icon_wrap_size_1 d_block social_links_color"><i class="icon-flickr-1"></i></a></li>
    <?php endif;?>

    <?php if($socialYoutube = $this->getBlockConfig('social/social_youtube')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialYoutube;?>" class=" youtube circle icon_wrap_size_1 d_block social_links_color"><i class="icon-youtube-play"></i></a></li>
    <?php endif;?>

    <?php if($socialVimeo = $this->getBlockConfig('social/social_vimeo')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialVimeo;?>" class=" vimeo circle icon_wrap_size_1 d_block social_links_color"><i class="icon-vimeo"></i></a></li>
    <?php endif;?>

    <?php if($socialInstagram = $this->getBlockConfig('social/social_instagram')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialInstagram;?>" class=" instagram circle icon_wrap_size_1 d_block social_links_color"><i class="icon-instagramm"></i></a></li>
    <?php endif;?>

    <?php if($socialLinkedin = $this->getBlockConfig('social/social_linkedin')):?>
        <li class="m_right_8"><a target="_blank" href="<?php echo $socialLinkedin;?>" class="linkedin circle icon_wrap_size_1 d_block social_links_color"><i class="icon-linkedin-squared"></i></a></li>
    <?php endif;?>

</ul>