<!--ENGLISH GRID-->
<p class="mission">CustomUSB is a service oriented customized USB products designer, manufacturer, and distributor<br> specializing in custom USB product development, and the creation of exact scale replicas of<br> licensed products for retail sale.</p>

<section class="cf">
    <div class="figwrap">
        <figure class="Feature curl">
            <a href="/flash-drives/" title="Browse All USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/01.jpg') ?>" alt="All USB Flash Drives">
                <h2>Browse All Flash Drives</h2>
            </a>
            <p>We have strong design and manufacturing capabilities that allow CustomUSB to output a large volume of fully customized USB drives and other cool consumer electronics and gadgets. We can handle product design, project management, domestic assembly, laser marking and printing, content management, quality control, sales, financing, fulfillment, and distribution.</p>
            <figcaption>
                <!--<h4>Safari</h4>-->
                <span>The USB flash drive is our flagship product. We offer the widest selection of promotional memory sticks in the world.</span>
                <a href="/flash-drives/" title="All USB Flash Drives">Take a Look!</a>
            </figcaption>
        </figure>
    </div>

    <div class="figwrap">
        <figure class="Feature curl">
            <a href="/custom-shape-flash-drives/" title="Custom Shape USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/05.jpg') ?>" alt="100% Custom USB Flash Drives">
                <h1>100<span class="oddball">%</span> Custom Flash Drives</h1>
            </a>
            <p>Our services include complete design and manufacturing of USB flash drive housing and hardware as well as customized consumer electronics, domestic laser engraving and printing, government grade encryption, and other data services all delivered in fully customized and developed packaging for a completely retail feel to the product.</p>
            <figcaption>
                <!--<h4>Safari</h4>-->
                <span>We can affordably create a one-of-a-kind custom USB flash drive design just for you. Your imagination is the only limit.</span>
                <a href="/custom-shape-flash-drives/" title="100% Custom Shape USB Flash Drives">Take a Look!</a>
            </figcaption>
        </figure>
    </div>
</section>

<section class="cf">
    <div class="figwrap">
        <figure class="curl">
            <a href="https://store.customusb.com" title="CustomUSB Web Store">
                <img src="<?php echo $this->getSkinUrl('images/featured/01 (1).jpg') ?>" alt="CustomUSB Web Store">
                <h3>CustomUSB Webstore</h3>
            </a>
        </figure>
    </div>

    <div class="figwrap">
        <figure class="curl">
            <a href="/rush/" title="Instant Order Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/05 (1).jpg') ?>" alt="Rush Order USB Flash Drives">
                <h3>Instant Order Flash Drives</h3>
            </a>
        </figure>
    </div>
</section>

<section class="cf">
    <div class="Category figwrap">
        <figure class="curl">
            <a href="/capless-flash-drives/" title="Capless USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/02.jpg') ?>" alt="Capless USB Flash Drives">
                <h3>Capless Designs</h3>
            </a>
        </figure>
    </div>
    <div class="Category figwrap">
        <figure class="curl">
            <a href="/wood-flash-drives/" title="Wood USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/06.jpg') ?>" alt="Wood USB Flash Drives">
                <h3>Wood Style USB</h3>
            </a>
        </figure>
    </div>
    <div class="Category figwrap">
        <figure class="curl">
            <a href="/metal-flash-drives/" title="Metal USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/01 (2).jpg') ?>" alt="Metal USB Flash Drives">
                <h3>Metal Style USB</h3>
            </a>
        </figure>
    </div>
    <div class="Category figwrap">
        <figure class="curl">
            <a href="/usb-business-cards/" title="Credit Card Style USB Flash Drives">
                <img src="<?php echo $this->getSkinUrl('images/featured/01 (3).jpg') ?>" alt="Wallet Card USB Flash Drives">
                <h3>Business Card<br>USB Drives</h3>
            </a>
        </figure>
    </div>
</section>

<p class="mission cf"><strong>What sets us apart from the competition? Our ability to listen to our customers!</strong></p>

<p>We work with marketing and advertising agencies to provide customized USB flash drives for ad campaigns and PR use - fulfilling orders with short delivery times and complex technical specifications. We have earned the trust of <strong>thousands</strong> of clients, inlcuding these fine companies:</p>

