<?php if($this->getBlockConfig('menu/menu_type') == 'side_menu'):?>
    <?php
        $illusion = $this->helper('illusion_settings');
        $_helper= Mage::helper('catalog/category');
        $_categories = $illusion->getCategories();

        $currentUrl = $this->getCurrentUrl();
        $homeUrl = $this->getUrl();
        $logoSrc = Mage::getStoreConfig('design/header/logo_src');
        $catalogSearchHelper =  $this->helper('catalogsearch');

    ?>

    <!--side menu-->
    <button id="open_side_menu" class="icon_wrap_size_2 circle color_black">
        <i class="icon-menu"></i>
    </button>
    <div id="side_menu">
        <header class="m_bottom_30 d_table w_full">
            <!--logo-->
            <div class="d_table_cell half_column v_align_m">
                <a href="<?php echo $this->getUrl('');?>">
                    <img src="<?php echo $this->getSkinUrl($logoSrc); ?>" alt="<?php echo $this->getLogoAlt() ?>">
                </a>
            </div>
            <!--close sidemenu button-->
            <div class="d_table_cell half_column v_align_m t_align_r">
                <button class="icon_wrap_size_2 circle color_grey_light_2 d_inline_m" id="close_side_menu">
                    <i class="icon-cancel"></i>
                </button>
            </div>
        </header>
        <hr class="divider_type_4 m_bottom_20">
        <!--searchform-->
        <form role="search" class="m_bottom_20 relative type_2" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
            <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>"  class="input-text r_corners fw_light bg_light w_full" placeholder="Search" />
            <button class="color_grey_light color_purple_hover tr_all" type="submit">
                <i class="icon-search"></i>
            </button>
        </form>
        <hr class="divider_type_4 m_bottom_25">
        <!--main menu-->
        <nav>
            <ul class="side_main_menu fw_light">

                <?php if($illusion->getConfig('menu/menu_home') == 1):?>
                    <li class="container3d relative f_xs_none m_bottom_10 <?php if($currentUrl == $homeUrl) echo 'current';?>" >
                        <a class="color_dark fs_large relative r_xs_corners side_menu_text_color" href="<?php echo $this->getUrl();?>"><?php echo $this->__('Home');?></a>
                    </li>
                <?php endif;?>

                <?php foreach($_categories as $_category):?>
                <?php $categoryChildren = $_category->getChildren(); ?>
                    <?php ;?>
                    <li class="<?php if($categoryChildren->count()) echo ' has_sub_menu '?> m_bottom_10 <?php if($this->getAppearsInCategory($_category)) echo ' current active';?>">
                        <a class="d_block relative fs_large color_light_2 color_blue_hover side_menu_text_color" href="<?php echo $_helper->getCategoryUrl($_category);?>"><?php echo $_category->getName();?>
                        <?php if($categoryChildren->count()):?>
                            <ul class="<?php if(!$this->getAppearsInCategory($_category)) echo ' d_none ';?> m_top_10">
                                <?php foreach($categoryChildren as $_categoryChild) : ?>
                                    <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId());?>
                                    <?php $categoryGrandchildren = $_categoryChild->getChildren(); ?>

                                    <li class="m_bottom_10 <?php if($categoryGrandchildren->count()) echo ' has_sub_menu '?> <?php if($this->getAppearsInCategory($_categoryChild)) echo ' current active';?>">
                                        <a href="<?php echo $_helper->getCategoryUrl($_categoryChildModel);?>" class="d_block relative color_light_2 color_blue_hover side_menu_text_color"><?php echo $_categoryChildModel->getName();?></a>
                                        <?php if($categoryGrandchildren->count()):?>
                                            <ul class="<?php if(!$this->getAppearsInCategory($_categoryChild)) echo ' d_none ';?> m_top_10">
                                                <?php foreach($categoryGrandchildren as $_categoryChild) : ?>
                                                    <?php $_categoryChildModel = Mage::getModel('catalog/category')->load($_categoryChild->getId());?>
                                                    <li class="m_bottom_10 <?php if($this->getAppearsInCategory($_categoryChild)) echo ' current active';?>">
                                                        <a href="<?php echo $_helper->getCategoryUrl($_categoryChildModel);?>" class="d_block relative color_light_2 color_blue_hover side_menu_text_color"><?php echo $_categoryChildModel->getName();?></a>
                                                    </li>
                                                <?php endforeach;?>
                                            </ul>
                                        <?php endif;?>
                                    </li>
                                <?php endforeach;?>
                            </ul>
                        <?php endif;?>
                        </a>
                    </li>
                <?php endforeach;?>
                <?php if(Mage::getStoreConfig('blog/blog/enabled')):?>
                    <li class="m_bottom_10  <?php if($this->getCurrentUrl() == Mage::getBaseUrl().Mage::getStoreConfig('blog/blog/route')) echo ' current ';?>" >
                        <a class="d_block relative fs_large color_light_2 color_blue_hover side_menu_text_color" href="<?php echo Mage::getBaseUrl().Mage::getStoreConfig('blog/blog/route');?>"><?php echo Mage::getStoreConfig('blog/blog/title');?>
                            <i class="icon-angle-down d_inline_m no_children"></i>
                        </a>
                    </li>
                <?php endif;?>
            </ul>
        </nav>
    </div>
<?php endif;?>