<div class="relative f_right dropdown_2_container shoppingcart t_left">
    <button class="icon_wrap_size_2 header_cart_icon_color header_cart_icon_border_color circle tr_all">
        <i class="icon-basket tr_inherit"></i>
    </button>
    <div class="dropdown_2 bg_light shadow_1 tr_all p_top_0">
        <div class="sc_header bg_light_2 fs_small color_grey">
            Recently added item(s)
        </div>
        <ul class="added_items_list">
            <li class="clearfix lh_large m_bottom_20 relative">
                <a href="#" class="d_block f_left m_right_10"><img src="<?php echo $this->getSkinUrl('images/sc_img_1.jpg');?>" alt=""></a>
                <div class="f_left item_description lh_ex_small">
                    <a href="#" class="color_dark fs_medium d_inline_b m_bottom_3">Duis ac turpis</a>
                    <p class="color_grey_light fs_small">Product Code PS34</p>
                </div>
                <div class="f_right fs_small lh_medium d_xs_none">
                    <span class="color_grey">1 x </span><span class="color_dark">$79.00</span>
                </div>
                <i class="icon-cancel-circled-1 color_grey_light_2 fs_large color_dark_hover tr_all"></i>
            </li>
            <li class="clearfix lh_large m_bottom_20 relative">
                <a href="#" class="d_block f_left m_right_10"><img src="<?php echo $this->getSkinUrl('images/sc_img_2.jpg');?>" alt=""></a>
                <div class="f_left item_description lh_ex_small">
                    <a href="#" class="color_dark fs_medium d_inline_b m_bottom_3">Integer rutrum ante eu lacus</a>
                    <p class="color_grey_light fs_small">Product Code PS34</p>
                </div>
                <div class="f_right fs_small lh_medium d_xs_none">
                    <span class="color_grey">1 x </span><span class="color_dark">$76.00</span>
                </div>
                <i class="icon-cancel-circled-1 color_grey_light_2 fs_large color_dark_hover tr_all"></i>
            </li>
            <li class="clearfix lh_large m_bottom_20 relative">
                <a href="#" class="d_block f_left m_right_10"><img src="<?php echo $this->getSkinUrl('images/sc_img_3.jpg');?>" alt=""></a>
                <div class="f_left item_description lh_ex_small">
                    <a href="#" class="color_dark fs_medium d_inline_b m_bottom_3">Vestibulum libero nisl</a>
                    <p class="color_grey_light fs_small">Product Code PS34</p>
                </div>
                <div class="f_right fs_small lh_medium d_xs_none">
                    <span class="color_grey">1 x </span><span class="color_dark">$189.00</span>
                </div>
                <i class="icon-cancel-circled-1 color_grey_light_2 fs_large color_dark_hover tr_all"></i>
            </li>
        </ul>
        <div class="total_price bg_light_2 t_align_r fs_medium m_bottom_15">
            <ul>
                <li class="color_dark">Tax: <span class="d_inline_b m_left_15 price t_align_l">$0.00</span></li>
                <li class="color_dark">Discount: <span class="d_inline_b m_left_15 price t_align_l">$37.00</span></li>
                <li class="color_dark"><span class="fw_ex_bold">Total:</span> <span class="fw_ex_bold d_inline_b m_left_15 price t_align_l color_pink">$999.00</span></li>
            </ul>
        </div>
        <div class="clearfix border_none p_top_0 sc_footer">
            <a href="#" class="button_type_5 d_block color_pink transparent f_right r_corners tr_all fs_medium m_left_5">Checkout</a>
            <a href="#" class="button_type_5 d_block color_dark f_right r_corners color_pink_hover tr_all fs_medium">View Cart</a>
        </div>
    </div>
</div>