<?php
    $blogName       =   Mage::getStoreConfig('blog/blog/title');
    $blogDescription =  Mage::getStoreConfig('blog/blog/description');
    $enabled        =   Mage::getStoreConfig('blog/blog/enabled');
    $enabledHome    =   Mage::getStoreConfig('blog/blog/enabled_homepage');
    $animationsEnable = Mage::getStoreConfig('illusion_settings/layout/animations_enable');
?>

<?php $posts = $this->getPosts(); ?>
<?php if($enabled && $enabledHome && $posts->count()):?>
<section class="section_offset bg_light_2">
    <div class="container">
        <h3 class="color_dark fw_light m_bottom_15 t_align_c" <?php if($animationsEnable):?>data-appear-animation="bounceInLeft"<?php endif;?>><?php echo $blogName;?></h3>
        <p class="m_bottom_35 t_align_c" <?php if($animationsEnable):?>data-appear-animation="bounceInLeft"<?php endif;?> data-appear-animation-delay="200"><?php echo $blogDescription;?></p>
        <div class="relative">
            <div class="row">
                <div class="owl-carousel" data-plugin-options='{"singleItem":false,"itemsCustom":[[992,4],[768,3],[450,2],[10,1]]}' data-nav="ln_nav_">
                    <?php foreach ($posts as $post): ?>
                        <figure class="col-lg-12 col-md-12 col-sm-12" <?php if($animationsEnable):?>data-appear-animation="fadeInUp"<?php endif;?>>
                            <!--image-->
                            <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
                                <img src="<?php echo $this->getResizedImage($post->getImage(),270,155, true, true);?>" width="270" />
                                <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
                                    <a href="<?php echo $post->getAddress(); ?>" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                                        <i class="icon-link"></i>
                                    </a>
                                </div>
                            </div>
                            <!--description-->
                            <figcaption>
                                <h6 class="lh_large m_bottom_3"><a href="<?php echo $post->getAddress(); ?>" class="color_dark tr_all blog_title"><?php echo $post->getTitle(); ?></a></h6>
                                <?php $postCats = $post->getCats(); ?>
                                <!--project's info-->
                                <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
                                    <li class="m_right_15 relative d_inline_m">
                                        <a href="<?php echo $post->getAddress(); ?>" class="color_grey fs_small">
                                            <i><?php echo $post->getCreatedTime(); ?></i>
                                        </a>
                                    </li>
                                    <?php if ($this->getCommentsEnabled()): ?>
                                        <li class="m_right_15 relative d_inline_m">
                                            <a href="<?php echo $post->getAddress(); ?>#postComment" class="color_scheme_hover blog_comments">
                                                <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all"><?php echo ($post->getCommentCount()) ? $post->getCommentCount() : 0;?></i>
                                            </a>
                                        </li>
                                    <?php endif;?>
                                </ul>
                                <p class="m_bottom_12 color_default"><?php echo $post->getPostContent(); ?></p>
                            </figcaption>
                        </figure>
                    <?php endforeach;?>
                </div>
            </div>

            <?php if(count($posts) > 3):?>
                <button class="icon_wrap_size_4 circle color_grey_light carousel_color carousel_border_color carousel_tr_all color_blue_hover ln_nav_prev d_md_none" <?php if($animationsEnable):?>data-appear-animation="fadeIn"<?php endif;?>>
                    <i class="icon-left-open-big"></i>
                </button>
                <button class="icon_wrap_size_4 circle color_grey_light carousel_color carousel_border_color tr_all color_blue_hover ln_nav_next d_md_none" <?php if($animationsEnable):?>data-appear-animation="fadeIn"<?php endif;?>>
                    <i class="icon-right-open-big"></i>
                </button>
            <?php endif;?>

        </div>
    </div>
</section>
<?php endif;?>
