<div class="tabs m_bottom_50 m_xs_bottom_30">
    <!--tabs nav-->
    <ul class="tabs_nav type_3 hr_list d_inline_b d_md_block m_bottom_30 m_xs_bottom_20">
        <li class="f_md_none"><a href="#recent" class="color_dark d_block n_sc_hover tr_all_medium"><?php echo $this->__('Recent') ?></a></li>
        <li class="f_md_none"><a href="#tags" class="color_dark d_block n_sc_hover tr_all_medium"><?php echo $this->__('Tags') ?></a></li>
        <li class="f_md_none"><a href="#comments" class="color_dark d_block n_sc_hover tr_all_medium"><?php echo $this->__('Comments') ?></a></li>
    </ul>
    <!--tabs content-->
    <div id="recent">
        <!--recent-->
        <?php if ($posts = $this->getRecent()): ?>
            <?php foreach ($posts as $post): ?>
                <article class="clearfix m_bottom_35 m_xs_bottom_20">
                    <a href="<?php echo $post->getAddress();?>" class="d_block r_corners wrapper f_left m_right_20 m_md_right_10 m_xs_right_20 f_sm_none m_sm_bottom_10 d_sm_inline_b d_xs_block f_xs_left m_xs_bottom_0">
                        <img src="<?php echo $this->getResizedImage($post->getImage(), 80, 80, true);?>" width="80" height="80"/>
                    </a>
                    <a href="<?php echo $post->getAddress();?>" class="color_dark d_block lh_medium m_bottom_5"><b><?php echo $post->getTitle();?></b></a>
                    <ul class="dotted_list color_grey_light_2 article_stats">
                        <li class="m_right_15 relative d_inline_m">
                            <span class="fs_small color_grey">
                                <i><?php echo $this->formatDate($post->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></i>
                            </span>
                        </li>
                        <?php $postCats = $post->getCats(); ?>
                        <?php if (!empty($postCats)): ?>
                            <li class="m_right_15 relative d_inline_m">
                                <?php foreach ($postCats as $title => $url): ?>
                                    <a href="<?php echo $url; ?>" class="fs_medium color_grey"><i><?php echo $title; ?></i></a>
                                <?php endforeach; ?>
                            </li>
                        <?php endif;?>
                    </ul>
                </article>
            <?php endforeach;?>
        <?php endif;?>
    </div>
    <div id="tags">
        <?php echo $this->getChildHtml('blog_tags'); ?>
    </div>
    <div id="comments">
        <?php $comments = $this->getComments();?>
        <ul class="hr_list vr_list_type_2 fw_light color_grey lh_medium">
            <?php if($comments->count()):?>
                <?php foreach($comments as $comment):?>
                    <li class="m_bottom_15">
                        <i class="icon-comment-empty m_right_8 fs_large color_grey_light_2 d_block f_left"></i>
                        <span class="color_grey"><?php echo $comment->getUser();?></span> on <a href="<?php echo $comment->getAddress();?>" class="color_dark"><b><?php echo $comment->getTitle();?></b></a>
                    </li>
                <?php endforeach;?>
            <?php endif;?>

        </ul>

    </div>
</div>
<div class="m_bottom_45 m_xs_bottom_30">
    <h5 class="fw_light color_dark m_bottom_23"><?php echo $this->__('Categories') ?></h5>
    <!--tags list-->
    <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
        <ul class="vr_list_type_4 color_dark fw_light">
            <?php $cats = $this->getCategories(); ?>
            <?php foreach ($cats as $cat): ?>
                <li class="m_bottom_12">
                    <a href="<?php echo $cat->getAddress(); ?>" class="color_dark d_inline_b">
                        <span class="icon_wrap_size_0 circle color_grey_light_5 d_block tr_inherit f_left">
                            <i class="icon-angle-right"></i>
                        </span>
                        <?php echo $cat->getTitle(); ?>
                    </a>
                </li>
            <?php endforeach;?>
        </ul>
    <?php endif;?>
</div>

<script type="text/javascript">
    jQuery(function(){
        jQuery('.tabs').easytabs({tabActiveClass: "active"})
    });
</script>
