<section class="section_offset bg_light_2">
<div class="container">
<h3 class="color_dark fw_light m_bottom_15 t_align_c" data-appear-animation="bounceInLeft">Latest News</h3>
<p class="m_bottom_35 t_align_c" data-appear-animation="bounceInLeft" data-appear-animation-delay="200">Proin dictum elementum velit. Fusce euismod consequat ante. </p>
<div class="relative">
<div class="row">
<div class="owl-carousel" data-plugin-options='{"singleItem":false,"itemsCustom":[[992,4],[768,3],[450,2],[10,1]]}' data-nav="ln_nav_">
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/blog_img_7.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/blog_img_7.jpg');?>" data-group="latest_news" data-title="Title 1" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Endrerit sit amet, tincidunt ac</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-doc-text-inv"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="200">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/shop_img_5.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/shop_img_5.jpg');?>" data-group="latest_news" data-title="Title 2" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Vivamus eget nibh</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-quote"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="400">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/portfolio_img_6.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/portfolio_img_6.jpg');?>" data-group="latest_news" data-title="Title 3" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Aliquam dapibus tincidunt</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-picture"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="600">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/home_img_2.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/home_img_5.jpg');?>" data-group="latest_news" data-title="Title 4" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Fusce euismod consequat ante</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-picture"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="800">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/portfolio_img_12.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/portfolio_img_12.jpg');?>" data-group="latest_news" data-title="Title 5" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Endrerit sit amet, tincidunt ac</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-doc-text-inv"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="1000">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/portfolio_img_1.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/portfolio_img_1.jpg');?>" data-group="latest_news" data-title="Title 6" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Vivamus eget nibh</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-quote"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="1200">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/home_img_4.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/home_img_7.jpg');?>" data-group="latest_news" data-title="Title 7" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Aliquam dapibus tincidunt</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-picture"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
<figure class="col-lg-12 col-md-12 col-sm-12" data-appear-animation="fadeInUp" data-appear-animation-delay="1400">
    <!--image-->
    <div class="popup_wrap relative r_corners wrapper m_bottom_20 db_xs_centered">
        <img src="<?php echo $this->getSkinUrl('images/home_img_3.jpg');?>" alt="">
        <div class="popup_buttons tr_all_long w_md_full t_md_align_c">
            <a href="<?php echo $this->getSkinUrl('images/home_img_6.jpg');?>" data-group="latest_news" data-title="Title 8" class="jackbox icon_wrap_size_3 color_light n_sc_hover d_block circle f_left m_right_10 f_md_none d_md_inline_b">
                <i class="icon-plus"></i>
            </a>
            <a href="#" class="icon_wrap_size_3 color_light n_sc_hover d_block circle f_left f_md_none d_md_inline_b">
                <i class="icon-link"></i>
            </a>
        </div>
    </div>
    <!--description-->
    <figcaption>
        <h6 class="lh_large m_bottom_3"><a href="#" class="color_dark tr_all">Fusce euismod consequat ante</a></h6>
        <!--project's info-->
        <ul class="dotted_list m_bottom_8 color_grey_light_2 lh_ex_small">
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey_light_2 fs_small">
                    <i class="icon-picture"></i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_grey fs_small">
                    <i>June 29,2013</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="fs_medium color_grey"><i>Mobile</i></a>,
                <a href="#" class="fs_medium color_grey"><i>Technology</i></a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_scheme_hover">
                    <i class="icon-chat-empty m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">12</i>
                </a>
            </li>
            <li class="m_right_15 relative d_inline_m">
                <a href="#" class="color_red_hover">
                    <i class="icon-heart-empty-1 m_right_2 color_grey_light_2 tr_all"></i><i class="fs_medium color_grey tr_all">35</i>
                </a>
            </li>
        </ul>
        <p class="m_bottom_12">Vivamus eget nibh. Etiam cursus leo vel metus. Nulla facilisi. Aenean nec eros. Vestibulum ante ipsum primis in faucibus orci luctus et...</p>
        <div class="clearfix">
            <a href="#" class="color_purple color_pink_hover f_left d_block m_right_20 fw_light">
                                                        <span class="d_inline_m m_right_5 icon_wrap_size_0 circle color_grey_light tr_all">
                                                            <i class="icon-angle-right"></i>
                                                        </span>
                Read More
            </a>
        </div>
    </figcaption>
</figure>
</div>
</div>
<!--carousel nav-->
<button class="icon_wrap_size_4 circle color_grey_light tr_all color_blue_hover ln_nav_prev d_md_none" data-appear-animation="fadeIn">
    <i class="icon-left-open-big"></i>
</button>
<button class="icon_wrap_size_4 circle color_grey_light tr_all color_blue_hover ln_nav_next d_md_none" data-appear-animation="fadeIn">
    <i class="icon-right-open-big"></i>
</button>
</div>
</div>
</section>