
<!--iosslider slider-->
<section class="relative iosslider w_full">
    <!--slider-->
    <div class="slider">
        <div class="slide">
            <img src="<?php echo $this->getSkinUrl('images/slide_04.jpg');?>" alt="">
            <div class="item animate_ftr tr_all_medium d_xs_none t_align_c">
                <h1 class="fw_ex_light color_light tt_uppercase">The biggest</h1>
                <p class="slider_title_1 fw_ex_bold color_light tt_uppercase lh_ex_small m_bottom_23 m_sm_bottom_5">Sale</p>
                <p class="color_light m_bottom_25 m_sm_bottom_5">Suspendisse sollicitudin velit sed leo. Ut pharetra<br>augue nec augue. </p>
                <a href="#" class="button_type_3 d_inline_b color_light transparent color_purple_hover r_corners tr_all tt_uppercase fs_medium d_block">Shop Now!</a>
            </div>
        </div>
        <div class="slide">
            <img src="<?php echo $this->getSkinUrl('images/slide_05.jpg');?>" alt="">
            <div class="item_2 animate_ftr tr_all_medium t_align_c d_xs_none">
                <div class="container">
                    <p class="fw_ex_bold color_light tt_uppercase slider_title_2 lh_ex_small">Find sunglasses</p>
                    <p class="fw_ex_light color_dark tt_uppercase slider_title_2 lh_ex_small m_bottom_20 m_md_bottom_10 m_sm_bottom_0">That Suited to you!</p>
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <img src="<?php echo $this->getSkinUrl('images/slide_layer_1.png');?>" alt="">
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <img src="<?php echo $this->getSkinUrl('images/slide_layer_2.png');?>" alt="">
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                            <img src="<?php echo $this->getSkinUrl('images/slide_layer_3.png');?>" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="slide">
            <img src="<?php echo $this->getSkinUrl('images/slide_06.jpg');?>" alt="">
            <div class="item_3 animate_ftr tr_all_medium d_xs_none">
                <p class="slider_title_1 fw_ex_bold color_light tt_uppercase lh_ex_small">New</p>
                <h1 class="fw_ex_light color_light slider_title_3 tt_uppercase m_bottom_10 m_sm_bottom_0">Arrivals</h1>
                <p class="color_light m_bottom_25 m_sm_bottom_5">Nam elit agna, endrerit sit amet, tincidunt ac, viverra<br>sed, nulla. Donec porta diam eu massa. Quisque diam<br>lorem, interdum vitae, dapibus ac.</p>
                <div class="clearfix d_xs_none">
                    <a href="#" class="button_type_3 color_light transparent color_scheme_hover r_corners tr_all tt_uppercase fs_medium d_block f_left m_right_10">Shop For Men</a>
                    <a href="#" class="button_type_3 color_light transparent color_pink_hover r_corners tr_all tt_uppercase fs_medium d_block f_left">Shop For Women</a>
                </div>
            </div>
        </div>
    </div>
    <!--nav-->
    <button class="ios_nav_prev"></button>
    <button class="ios_nav_next"></button>
</section>